---
abstract: 'set of plugins for working with Catalyst'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
  - 'Tomas Doran <bobtfish@bobtfish.net>'
build_requires:
  Carp: 0
  Dist::Zilla::Tester: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Catalyst
no_index:
  directory:
    - corpus
requires:
  Catalyst::Helper: 1.30
  Dist::Zilla::File::FromCode: 0
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::MintingProfile::ShareDir: 0
  Dist::Zilla::Role::ModuleMaker: 0
  Moose: 0
  Path::Class: 0
  namespace::autoclean: 0
  perl: 5.006
resources:
  bugtracker: http://github.com/xenoterracide/Dist-Zilla-Plugin-Catalyst/issues
  repository: git://github.com/xenoterracide/Dist-Zilla-Plugin-Catalyst.git
version: 0.16
